(() => {
'use strict';
const {InventoryShift,catalog,groups,suppliers}=InventoryModel;
const root=document.querySelector('#inventory');
const money=n=>'$'+n.toFixed(2);
let shift,paused=true,category='Coffee',selected='Original Blend',supplier='local',timer;
function metric(label,value){return `<div class="metric"><small>${label}</small><b>${value}</b></div>`;}
function mount(){clearInterval(timer);shift=new InventoryShift();paused=true;category='Coffee';selected='Original Blend';supplier='local';root.innerHTML=`<header><div><span class="eyebrow">rISE Café · Management desk</span><h1>Inventory Manager</h1><p>The right stock. At the right time.</p></div><div class="controls"><b id="clock"></b><button id="pause">Start shift</button><button id="help">How to play</button><a href="index.html">Role selection</a></div></header>
<section class="hero"><div><span class="eyebrow">Your café is counting on you</span><h2>A well-stocked café starts here.</h2><p>Balance tomorrow’s deliveries with today’s demand. Watch your shelves, protect your budget, and keep every customer’s favorite on the menu.</p></div><img src="assets/roles.png" alt="The café team ready for their shift"></section>
<div id="alerts" class="alert" role="status"></div><section id="metrics" class="metrics" aria-label="Live shift performance"></section>
<div class="board"><section class="panel"><h2>The stockroom <span class="eyebrow">· Recipe portions</span></h2><nav class="tabs" aria-label="Inventory categories">${Object.keys(groups).map(g=>`<button data-group="${g}">${g}</button>`).join('')}</nav><div class="shelves" id="shelves"></div></section>
<aside><section class="panel"><h2>Supplier order</h2><form id="order-form"><label for="product">Ingredient or supply</label><select id="product">${catalog.map(p=>`<option>${p.name}</option>`).join('')}</select><label for="supplier">Supplier</label><select id="supplier">${Object.entries(suppliers).map(([k,s])=>`<option value="${k}" ${k===supplier?"selected":""}>${s.name}</option>`).join('')}</select><label for="quantity">Quantity (1–100 portions)</label><input id="quantity" type="number" min="1" max="100" step="1" value="10" required><div id="quote" class="quote"></div><button class="primary" id="buy">Place supplier order</button><div id="message" class="message" role="status"></div></form><p class="tip">Value: 20% cheaper, 8 min delivery, 85% quality. Local: standard cost, 4 min, 100% quality. Artisan: 30% more, 2 min, 115% quality. Lower quality discounts revenue; higher quality preserves freshness-sensitive service without raising menu prices.</p></section>
<section class="panel"><h2>Menu pricing</h2><form id="price-form"><div class="price-fields"><div><label for="drink-price">Drink price ($)</label><input id="drink-price" type="number" min="1" max="12" step=".25" value="5.5" required></div><div><label for="bakery-price">Bakery price ($)</label><input id="bakery-price" type="number" min="1" max="12" step=".25" value="4" required></div></div><button>Update menu prices</button><div id="price-message" class="message" role="status"></div></form><p class="tip">Prices above $5.50 / $4.00 reduce demand. Prices apply to future customers. Margin = (price − recipe cost) / price; markup = (price − recipe cost) / recipe cost.</p><div id="margin" class="quote"></div></section>
<section class="panel"><h2>On the way</h2><ul id="deliveries" class="deliveries"></ul></section></aside></div>
<section class="panel" style="margin-top:20px"><h2>Café activity</h2><ul id="activity" class="activity" aria-live="polite"></ul></section>
<footer>Inventory management · Supply chain · Demand forecasting · Safety stock · Reorder points · Engineering economics<br>One café minute passes every 3 seconds. This independent simulation does not share inventory or state with Barista Mode.</footer><dialog id="dialog"></dialog>`;
root.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{category=b.dataset.group;drawShelves();});
document.querySelector('#pause').onclick=()=>{if(shift.time>=shift.duration)return;paused=!paused;update();};
document.querySelector('#help').onclick=welcome;
document.querySelector('#product').onchange=e=>{selected=e.target.value;quote();};
document.querySelector('#supplier').onchange=e=>{supplier=e.target.value;quote();drawShelves();};
document.querySelector('#quantity').oninput=quote;
document.querySelector('#order-form').onsubmit=e=>{e.preventDefault();const error=shift.order(selected,Number(document.querySelector('#quantity').value),supplier);document.querySelector('#message').textContent=error||'Order placed. Delivery is on its way!';update();};
document.querySelector('#price-form').onsubmit=e=>{e.preventDefault();const drink=Number(document.querySelector('#drink-price').value),bakery=Number(document.querySelector('#bakery-price').value);if(![drink,bakery].every(n=>Number.isFinite(n)&&n>=1&&n<=12))return;shift.price('drink',drink);shift.price('bakery',bakery);document.querySelector('#price-message').textContent='Menu prices updated.';update();};
timer=setInterval(()=>{if(!paused&&!document.querySelector('#dialog').open){shift.tick();update();if(shift.time>=shift.duration){paused=true;summary();}}},3000);update();welcome();}
function drawShelves(){root.querySelectorAll('[data-group]').forEach(b=>b.classList.toggle('active',b.dataset.group===category));document.querySelector('#shelves').innerHTML=catalog.filter(p=>p.group===category).map(p=>{const qty=shift.qty(p.name),point=shift.reorder(p,supplier),status=qty===0?'critical':qty<=Math.max(1,point*.5)?'critical':qty<=point?'low':'healthy';const expiry=shift.stock[p.name].length?Math.min(...shift.stock[p.name].map(b=>b.expires))-shift.time:null;return `<article class="stock-card ${status}"><h3>${p.name}</h3><strong>${qty}</strong> <small style="display:inline">portions</small><div class="track"><i style="width:${Math.min(100,qty/Math.max(1,point*3)*100)}%"></i></div><span class="status">${qty===0?'OUT OF STOCK':status==='critical'?'CRITICALLY LOW':status==='low'?'GETTING LOW':'HEALTHY'}</span><small>${qty<=point?'REORDER RECOMMENDED':'Stock covers forecast'} · point: ${point}<br>Demand: ${shift.rate(p).toFixed(2)}/min · incoming: ${shift.incoming(p.name)}<br>${expiry===null?'Shelf empty':'Earliest expiry: '+expiry+' min'}</small><button data-order="${p.name}">Order supplies →</button></article>`;}).join('');root.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{selected=b.dataset.order;document.querySelector('#product').value=selected;quote();document.querySelector('#quantity').focus();});}
function quote(){const p=catalog.find(p=>p.name===selected),s=suppliers[supplier],qty=Number(document.querySelector('#quantity').value);document.querySelector('#quote').textContent=`${money(p.cost*s.multiplier)} / portion · ${s.lead} min lead time · ${money(p.cost*s.multiplier*(Number.isFinite(qty)?qty:0))} total. Reorder point: ${shift.reorder(p,supplier)} portions (forecast through lead time + safety stock).`;}
function update(){document.querySelector('#clock').textContent=`${shift.time} / 60 min`;document.querySelector('#pause').textContent=shift.time>=60?'Shift complete':paused?'Resume shift':'Pause shift';document.querySelector('#pause').disabled=shift.time>=60;document.querySelector('#buy').disabled=shift.time>=60;document.querySelector('#alerts').textContent=shift.phase()+(shift.time>=10&&shift.time<15?' · Oat Milk trend expected soon':shift.time>=25&&shift.time<30?' · RUSH EXPECTED SOON':'');document.querySelector('#metrics').innerHTML=metric('Purchasing budget left',money(shift.budget-shift.spent))+metric('Sales revenue',money(shift.revenue))+metric('Operating profit',money(shift.profit))+metric('Lost sales',shift.lost)+metric('Units wasted',shift.waste);drawShelves();quote();document.querySelector('#deliveries').innerHTML=shift.deliveries.length?shift.deliveries.map(d=>`<li><b>${d.qty} ${d.name}</b><br>${d.supplier} · arrives in ${d.at-shift.time} min</li>`).join(''):'<li>No deliveries pending.</li>';document.querySelector('#activity').innerHTML=shift.log.length?shift.log.map(l=>`<li>${l}</li>`).join(''):'<li>The doors are open. Review your stock before starting the clock.</li>';const mean=group=>catalog.filter(p=>p.group===group).reduce((s,p)=>s+p.cost,0)/groups[group].length;const drinkCost=['Coffee','Milk','Syrup','Topping'].reduce((s,g)=>s+mean(g),0)+3*.12,bakeryCost=mean('Bakery')+.12;document.querySelector('#margin').textContent=`Standard recipe estimates: drink ${money(drinkCost)} cost / ${Math.round((1-drinkCost/shift.prices.drink)*100)}% margin; bakery ${money(bakeryCost)} / ${Math.round((1-bakeryCost/shift.prices.bakery)*100)}% margin. Supplier mix changes actual profit.`;}
function welcome(){const d=document.querySelector('#dialog');d.innerHTML=`<h2>Welcome, Inventory Manager!</h2><p>Your café is open, and keeping it stocked is in your hands. Monitor ingredient levels, order supplies, and make sure the café has what it needs to serve its customers.</p><p>Every decision affects costs, waste, lost sales, and profit. You have a <b>$250 purchasing budget</b>, and supplier deliveries take time, so order wisely!</p><p>Your goal: keep the café stocked while staying within budget, reducing waste, preventing stockouts, and maximizing profit. Green means healthy, yellow means low, and red means critical or empty.</p><p>Reorder points use observed ingredient demand × (supplier lead time + safety coverage). Bakery spoils after 12 minutes; milk and chilled toppings after 24. Forecasts adapt as customer orders change. Prices can reduce demand, and cheaper supplier quality reduces sale revenue.</p><button class="primary" id="begin">Let’s stock the café →</button>`;if(!d.open)d.showModal();document.querySelector('#begin').onclick=()=>{d.close();paused=false;update();};}
function summary(){const d=document.querySelector('#dialog');d.innerHTML=`<h2>Shift complete! ${shift.score} / 100</h2><p>You served ${shift.served} of ${shift.requests} customers who accepted your prices.</p><div class="metrics">${metric('Stockout incidents',shift.stockouts)}${metric('Lost sales',shift.lost)}${metric('Lost sales value',money(shift.lostRevenue))}${metric('Units wasted',shift.waste)}${metric('Waste cost',money(shift.wasteCost))}${metric('Inventory purchases',money(shift.spent))}${metric('Sales revenue',money(shift.revenue))}${metric('Operating profit',money(shift.profit))}${metric('Average inventory', (shift.area/shift.duration).toFixed(1))}${metric('Holding costs',money(shift.holding))}</div><p class="summary-note">Score: 60 points for fulfilled demand, 20 for avoiding waste, and up to 20 for $200 operating profit. Stockouts count each missing ingredient per failed order. Profit = revenue − ingredients consumed (including opening stock) − waste cost − holding cost. Unsold, unexpired inventory remains an asset; purchasing cash flow = revenue − purchases − holding cost: <b>${money(shift.revenue-shift.spent-shift.holding)}</b>.</p><p>${shift.lost>shift.served?'Try ordering before the rush and accounting for supplier lead time.':shift.wasteCost>20?'Try smaller, more frequent bakery and milk deliveries to reduce spoilage.':'Keep adjusting safety stock as demand changes. Compare supplier speed against its extra cost.'}</p><button class="primary" id="replay">Try another shift</button> <a href="index.html">Role selection</a>`;d.showModal();document.querySelector('#replay').onclick=()=>{d.close();mount();};}
mount();
})();


