/* Queue-first mode. All times are elapsed simulation seconds. */
class QueueCafe extends Cafe {
 constructor(){super();this.duration=300;this.time=0;this.orders=[];this.id=0;this.activeId=null;this.events=[];this.arrivals=[0,30,60,90,120,150,180,200,220,240,260,280];this.nextArrival=0;this.jobs=[];this.rushIds=[];this.helperUnlocked=false;this.oven=null;this.peakQueue=0;this.manualOwner=null;this.ovenSlots=[null,null];}
 addOrder(){const o=super.addOrder();o.progress={syrup:0,milk:0,coffee:0,topping:0,baking:0};if(o.recipe.coffee){o.price+=4.75-({Small:4,Medium:4.75,Large:5.5}[o.recipe.size]);o.recipe.size='Medium';const first=o.recipe.topping;const extra=o.id===1?'Caramel Drizzle':o.id%2===0?'Cinnamon':'Chocolate Drizzle';o.recipe.topping=[first,...(first!==extra?[extra]:[])];o.toppingStrokes=[];o.appliedToppings=[];}return o;}
 accept(o=this.active){if(!o)return false;super.accept(o);if(o.recipe.coffee)o.selections.size='Medium';return true;}
 benchmark(o){/* 18 units/sec pouring + 4 ingredient selections, panel changes and handoff; baking overlaps. */const drink=o.recipe.coffee?Math.ceil(97/18+4*5+4):0;const food=o.recipe.bakery?25:0;return Math.max(drink,food)+5+(o.recipe.coffee?Math.max(0,o.recipe.topping.length-1)*6:0);}
 satisfaction(o){const wait=Math.max(0,this.time-o.arrived),target=this.benchmark(o);return Math.max(0,Math.round(wait<=target?100-9*wait/target:91-(wait-target)*.32));}
 scores(o=this.active){const s=super.scores(o);if(!s)return s;if(o.recipe.coffee){s.steps.topping=o.fills.topping??0;s.coffeeAccuracy=(FIELDS.reduce((sum,k)=>sum+s.steps[k],0)+100)/5;s.accuracy=Math.round(o.recipe.bakery?(s.coffeeAccuracy+s.bakeryAccuracy)/2:s.coffeeAccuracy);}s.satisfaction=Math.round(s.accuracy*.6+this.satisfaction(o)*.4);return s;}
 canStart(k,o=this.active){if(!o?.accepted)return false;if(k==='baking')return !!o.recipe.bakery&&this.ovenSlots.some(s=>!s)&&!o.bakeryResult&&!this.ovenSlots.some(s=>s?.id===o.id);if(!o.recipe.coffee||this.jobs.some(j=>j.id===o.id&&j.worker==='helper'))return false;const i=FIELDS.indexOf(k);return i>=0&&FIELDS.slice(0,i).every(f=>o.fills[f]!==undefined);}
 begin(k,o=this.active){return k==='baking'?this.loadOven(this.ovenSlots.findIndex(s=>!s),o?.recipe.bakery,o):false;}
 loadOven(slot,item,o=this.active){if(!Number.isInteger(slot)||slot<0||slot>1||this.ovenSlots[slot]||!MENU.bakery.includes(item)||!this.canStart('baking',o))return false;const job={id:o.id,key:'baking',item,slot,started:this.time,duration:20,worker:'oven'};this.ovenSlots[slot]={...job,ready:false};this.jobs.push(job);this.syncOven();return true;}
 syncOven(){this.oven=this.ovenSlots.find(Boolean)||null;}
 collectOven(slot){const food=this.ovenSlots[slot];if(!food?.ready)return false;const o=this.orders.find(o=>o.id===food.id);if(o)o.bakeryResult={correct:food.item===o.recipe.bakery,score:100,item:food.item};this.ovenSlots[slot]=null;this.syncOven();return true;}
 remakeBakery(o=this.active){if(!o?.bakeryResult)return false;o.bakeryResult=null;o.progress.baking=0;this.costs+=.6;return true;}
 finishStep(k,o=this.active){if(k==='topping')return this.finishToppings(o);if(!this.canPour(k,o))return false;this.pour(k,o.levels[k]??this.baseLevel(k,o),o);o.progress[k]=100;if(k==='topping')o.lid=true;return true;}
 retry(k,o=this.active){super.retry(k,o);if(o){o.toppingStrokes=[];o.appliedToppings=[];}if(o)for(const f of FIELDS.slice(FIELDS.indexOf(k)))o.progress[f]=0;}
 choose(k,v,o=this.active){if(o&&o.selections[k]!==v&&o.fills[k]!==undefined)this.retry(k,o);return super.choose(k,v,o);}
 complete(job,o){o.progress[job.key]=100;if(job.key==='baking'){if(this.ovenSlots[job.slot])this.ovenSlots[job.slot].ready=true;this.syncOven();}else if(job.key==='drink'){for(const k of FIELDS)o.selections[k]=o.recipe[k];for(const k of FIELDS)o.progress[k]=100;for(const k of FIELDS){o.fills[k]=100;o.levels[k]=FILL_TARGETS[k];}o.appliedToppings=[...o.recipe.topping];o.lid=true;o.helperDone=true;}else{o.fills[job.key]=100;o.levels[job.key]=FILL_TARGETS[job.key];if(job.key==='coffee'){o.fills.topping=100;o.levels.topping=97;o.lid=true;}}this.events.push({type:'station-done',id:o.id,key:job.key});}
 addToppingStroke(type,points,o=this.active){if(!o||!this.canStart('topping',o)||!MENU.topping.includes(type)||!points.length)return false;const clean=points.filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x>=105&&p.x<=355&&p.y>=25&&p.y<=185).map(p=>({x:p.x,y:p.y}));if(!clean.length)return false;const length=clean.reduce((sum,p,i)=>i?sum+Math.hypot(p.x-clean[i-1].x,p.y-clean[i-1].y):0,0);if(type!=='Cinnamon'&&length<35)return false;o.toppingStrokes.push({type,points:clean});o.appliedToppings=[...new Set(o.toppingStrokes.map(s=>s.type))];delete o.fills.topping;o.lid=false;o.progress.topping=Math.min(99,o.appliedToppings.filter(t=>o.recipe.topping.includes(t)).length/o.recipe.topping.length*100);return true;}
 finishToppings(o=this.active){if(!o||!this.canStart('topping',o)||!o.appliedToppings?.length)return false;const expected=o.recipe.topping,got=o.appliedToppings;const correct=expected.filter(t=>got.includes(t)).length,extras=got.filter(t=>!expected.includes(t)).length;o.fills.topping=Math.max(0,Math.round(100*correct/expected.length-25*extras));o.selections.topping=[...got];o.levels.topping=97;o.progress.topping=100;o.lid=true;return true;}
 tick(dt){if(this.finished||dt<=0||!Number.isFinite(dt))return;dt=Math.min(dt,this.duration-this.time);this.queueArea+=this.orders.length*dt;this.time+=dt;if(this.helper)this.costs+=dt*.03;
 if(this.time>=180&&!this.helperUnlocked){this.helperUnlocked=true;this.events.push({type:'rush'});}
 while(this.id<this.arrivals.length&&this.time>=this.arrivals[this.id]){const at=this.arrivals[this.id],o=this.addOrder();o.arrived=at;}
 this.rushIds=this.arrivals.map((at,i)=>at>=180&&i<this.id?i+1:0).filter(Boolean);this.nextArrival=this.arrivals[this.id]??Infinity;this.peakQueue=Math.max(this.peakQueue,this.orders.length);
 for(const job of [...this.jobs]){const o=this.orders.find(o=>o.id===job.id);if(!o){this.jobs=this.jobs.filter(j=>j!==job);continue;}const p=Math.min(100,(this.time-job.started)/job.duration*100);if(job.key==='drink'){for(const k of FIELDS)o.progress[k]=Math.max(o.progress[k],p);}else o.progress[job.key]=p;if(p>=100){this.complete(job,o);this.jobs=this.jobs.filter(j=>j!==job);}}
 if(this.helper&&!this.jobs.some(j=>j.worker==='helper')){const o=this.orders.find(o=>o.id!==this.manualOwner&&o.accepted&&o.recipe.coffee&&o.progress.topping<100&& !FIELDS.some(k=>o.fills[k]!==undefined)&&!this.jobs.some(j=>j.id===o.id&&j.worker==='player'));if(o)this.jobs.push({id:o.id,key:'drink',started:this.time,duration:14,worker:'helper'});}
 if(this.time>=this.duration){this.finished=true;this.events.push({type:'end'});}
 }
}
if(typeof module!=='undefined')module.exports={QueueCafe};
